### PR TITLE
Updated webpack to v3.7.1

### PR DESCRIPTION
**Pull request by marcinlichwala**
Fixed issue with babel-loader name in webpack.config.js
Added .idea files to gitignore

### CODE REVIEW

**Comment by nihey** [comment]
Thanks! I'll take a deeper look at it tomorrow!

**Comment by marcinlichwala** [comment]
@nihey, I had to update babel and eslint because it was very outdated and cause issues while installing on Ttavis. I can see that there is still an indentation issue. Please let me know if the dist files are correct. There are no automated tests for it now :(

**Comment by nihey** [comment]
>  Please let me know if the dist files are correct. 

@marcinlichwala, Everything seems correct, the `webpack.config.js` file was actually the most important part, but you've made more than that, thanks :+1: 

> I can see that there is still an indentation issue.

Yes! Probably my fault on that, the outdated ESLint was not covering that up, I'll fix it and merge.

**Comment by nihey** [comment]
Oh, I've forgot, a little tip: you can put `Fix #<Issue Number>`(e.g.: `Fix #42`) on your Pull Request text body or commit messages and it will automatically close the issue. No big deal here, but it may help you on the future!

[Source](https://help.github.com/articles/closing-issues-using-keywords/)

**Pull request merged**
